build_from:
  aarch64: "ghcr.io/hassio-addons/base-aarch64:15.0.0"
  amd64: "ghcr.io/hassio-addons/base-amd64:15.0.0"
  armhf: "ghcr.io/hassio-addons/base-armhf:15.0.0"
  armv7: "ghcr.io/hassio-addons/base-armv7:15.0.0"

args: {}

labels:
  org.opencontainers.image.title: "SFPLiberate"
  org.opencontainers.image.description: "Bluetooth companion for Ubiquiti SFP Wizard"
  org.opencontainers.image.source: "https://github.com/josiah-nelson/SFPLiberate"
  org.opencontainers.image.licenses: "MIT"
