build_from:
  aarch64: "ghcr.io/home-assistant/aarch64-base:3.22"
  amd64: "ghcr.io/home-assistant/amd64-base:3.22"
  armhf: "ghcr.io/home-assistant/armhf-base:3.22"
  armv7: "ghcr.io/home-assistant/armv7-base:3.22"

args:
  BUILD_VERSION: "{version}"

labels:
  org.opencontainers.image.title: "SFPLiberate"
  org.opencontainers.image.description: "Bluetooth companion for Ubiquiti SFP Wizard"
  org.opencontainers.image.source: "https://github.com/josiah-nelson/SFPLiberate"
  org.opencontainers.image.licenses: "MIT"
